services:
  139cas:
    restart: always
    volumes:
      - '/etc/139cas:/opt/openlist/data'
    ports:
      - '5244:5244'
      - '5245:5245'
    user: '0:0'
    environment:
      - OPENLIST_HTTP_PORT=5244
      - UMASK=022
      - TZ=Asia/Shanghai
    container_name: 139cas
    image: 'tianjian518/139cas:latest'
